runtime: go119
app_engine_apis: true

handlers:
- url: /favicon\.ico
  static_files: web/appengine/static/default/img/favicon.ico
  upload: web/appengine/static/default/img/favicon_32x32\.ico
  expiration: "1d"
- url: /sitemap\.xml
  static_files: web/appengine/static/default/xml/sitemap.xml
  upload: web/appengine/static/default/xml/sitemap\.xml
- url: /\.well-known/security\.txt
  static_files: web/appengine/static/default/.well-known/security.txt
  upload: web/appengine/static/default/\.well-known/security\.txt
  expiration: "1d"
- url: /robots\.txt
  static_files: web/appengine/static/default/robots.txt
  upload: web/appengine/static/default/robots\.txt
  expiration: "300s"
- url: /default/img
  static_dir: web/appengine/static/default/img
  expiration: "15d"
- url: /default/css
  static_dir: web/appengine/static/default/css
  expiration: "1h"
- url: /default
  static_dir: web/appengine/static/default
  expiration: "1h"
- url: /default_.*_
  static_dir: web/appengine/static/default
  expiration: "364d"
  secure: always
- url: /admin.*
  script: auto
  login: admin
  secure: always
- url: /.*
  script: auto
  secure: always
